### PR TITLE
Added travis testing framework

### PR DESCRIPTION
**Pull request by kkellerlbl**
There aren't any interesting tests yet, mostly just making sure that testing actually works and reports to Codecov.  I'm hoping this PR triggers a Travis build.

### CODE REVIEW

**Comment by kkellerlbl** [comment]
It worked!

**Comment by kkellerlbl** [comment]
I added a test script but I haven't set up the services in travis.yml yet, so these all fail in Travis.  The last commit skips the tests for now.

**Comment by kkellerlbl** [comment]
I need to figure out how to run tests without a valid token, since Travis won't have one.  I think Matt mentioned something about how to do this but I don't remember the details.

**Comment by mlhenderson** [comment]
Since the test data is public, you can pass in an empty token string "".  You'll want to have Travis clone the data_api repo so that you can run the services locally for your client tests.

**Comment by kkellerlbl** [comment]
Any objection to merging?  I have more tests to write but I'd like to get this one in so that future merges aren't too big.

**Comment by mlhenderson** [comment]
No objection here.

**Pull request merged**
